export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REDIRECTED = 'REDIRECTED';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';

export const GET_OWN_RECIPES_SUCCESS = 'GET_OWN_RECIPES_SUCCESS';
export const GET_INIT_USER_PROFILE_SUCCESS = 'GET_INIT_USER_PROFILE_SUCCESS';

export const GET_MOST_RECENT_APPROVED_RECIPES = 'GET_MOST_RECENT_APPROVED_RECIPES';

export const GET_MOST_RECENT_NOT_APPROVED_RECIPES_SUCCESS = 'GET_MOST_RECENT_NOT_APPROVED_RECIPES_SUCCESS';